packages:
  - apps/*
  - libs/*
  - packages/*

catalog:
  '@clerk/backend': ^2.15.0
  '@hono/zod-validator': ^0.7.3
  convex: ^1.31.2
  effect: ^3.19.14
  hono: ^4.9.9
  zod: ^4.3.5
  "ai": "6.0.94"
  "@ai-sdk/google": "3.0.30"
  "@ai-sdk/openai": "^3.0.30"
  "@opentelemetry/api": "^1.9.0"


catalogMode: manual

cleanupUnusedCatalogs: true
