// Mock recipes data
export const mockRecipes = [
	{
		id: "1",
		title: "Spaghetti Carbonara",
		description: "Classic Italian pasta dish with eggs, cheese, and pancetta",
		image: "/spaghetti-carbonara.png",
		cookTime: 25,
		difficulty: "Medium",
		servings: 4,
		rating: 4.8,
		tags: ["Italian", "Pasta", "Quick"],
		ingredients: ["Spaghetti", "Eggs", "Parmesan", "Pancetta", "Black Pepper"],
		canCook: true,
		variants: [],
		lastCooked: "2024-01-10",
	},
	{
		id: "2",
		title: "Chicken Tikka Masala",
		description: "Creamy tomato-based curry with tender chicken pieces",
		image: "/chicken-tikka-masala.png",
		cookTime: 45,
		difficulty: "Hard",
		servings: 6,
		rating: 4.9,
		tags: ["Indian", "Curry", "Spicy"],
		ingredients: ["Chicken Breast", "Tomatoes", "Cream", "Spices", "Onions"],
		canCook: false,
		variants: [
			{
				id: "2a",
				title: "Chicken Tikka Masala (Mild)",
				substitutions: ["Mild spices instead of hot"],
			},
		],
		lastCooked: null,
	},
	{
		id: "3",
		title: "Caesar Salad",
		description: "Fresh romaine lettuce with classic Caesar dressing",
		image: "/caesar-salad.png",
		cookTime: 15,
		difficulty: "Easy",
		servings: 2,
		rating: 4.5,
		tags: ["Salad", "Healthy", "Quick"],
		ingredients: ["Romaine Lettuce", "Parmesan", "Croutons", "Caesar Dressing"],
		canCook: true,
		variants: [],
		lastCooked: "2024-01-12",
	},
	{
		id: "4",
		title: "Beef Stir Fry",
		description: "Quick and healthy stir fry with fresh vegetables",
		image: "/beef-stir-fry.jpg",
		cookTime: 20,
		difficulty: "Easy",
		servings: 4,
		rating: 4.6,
		tags: ["Asian", "Quick", "Healthy"],
		ingredients: ["Beef", "Bell Peppers", "Broccoli", "Soy Sauce", "Garlic"],
		canCook: false,
		variants: [
			{
				id: "4a",
				title: "Chicken Stir Fry",
				substitutions: ["Chicken instead of beef"],
			},
		],
		lastCooked: null,
	},
];

// Mock recipe data
export const mockRecipe = {
	id: "1",
	title: "Spaghetti Carbonara",
	description:
		"Classic Italian pasta dish with eggs, cheese, and pancetta. A creamy, rich pasta that's perfect for a quick weeknight dinner.",
	image: "/spaghetti-carbonara-plated.jpg",
	cookTime: 25,
	difficulty: "Medium",
	servings: 4,
	rating: 4.8,
	tags: ["Italian", "Pasta", "Quick", "Comfort Food"],
	ingredients: [
		{ name: "Spaghetti", amount: "400g", available: true },
		{ name: "Eggs", amount: "4 large", available: true },
		{ name: "Parmesan Cheese", amount: "100g grated", available: true },
		{ name: "Pancetta", amount: "150g diced", available: false },
		{ name: "Black Pepper", amount: "1 tsp freshly ground", available: true },
		{ name: "Salt", amount: "to taste", available: true },
	],
	steps: [
		"Bring a large pot of salted water to boil and cook spaghetti according to package directions until al dente.",
		"While pasta cooks, heat a large skillet over medium heat and cook pancetta until crispy, about 5-7 minutes.",
		"In a bowl, whisk together eggs, grated Parmesan, and freshly ground black pepper.",
		"Reserve 1 cup of pasta cooking water, then drain the pasta.",
		"Immediately add hot pasta to the skillet with pancetta and toss to combine.",
		"Remove from heat and quickly stir in the egg mixture, adding pasta water gradually until creamy.",
		"Serve immediately with extra Parmesan and black pepper.",
	],
	nutritionInfo: {
		calories: 520,
		protein: "22g",
		carbs: "65g",
		fat: "18g",
	},
	advantages: [
		"Quick to make",
		"Uses simple ingredients",
		"Authentic Italian recipe",
	],
	canCook: false,
	missingIngredients: ["Pancetta"],
	lastCooked: "2024-01-10",
	variants: [],
};

export const difficultyColors = {
	Easy: "bg-green-100 text-green-800",
	Medium: "bg-yellow-100 text-yellow-800",
	Hard: "bg-red-100 text-red-800",
};
