/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteImport } from './routes/dev'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as appauthedRouteRouteImport } from './routes/(app)/(authed)/route'
import { Route as appauthedARouteImport } from './routes/(app)/(authed)/a'
import { Route as appauthedDashboardRouteRouteImport } from './routes/(app)/(authed)/dashboard/route'
import { Route as appauthedDashboardIndexRouteImport } from './routes/(app)/(authed)/dashboard/index'
import { Route as appauthedDashboardShoppingListIndexRouteImport } from './routes/(app)/(authed)/dashboard/shopping-list/index'
import { Route as appauthedDashboardRecipesIndexRouteImport } from './routes/(app)/(authed)/dashboard/recipes/index'
import { Route as appauthedDashboardMealPlansIndexRouteImport } from './routes/(app)/(authed)/dashboard/meal-plans/index'
import { Route as appauthedDashboardIngredientsIndexRouteImport } from './routes/(app)/(authed)/dashboard/ingredients/index'
import { Route as appauthedDashboardRecipesCreateRouteImport } from './routes/(app)/(authed)/dashboard/recipes/create'
import { Route as appauthedDashboardRecipesIdRouteImport } from './routes/(app)/(authed)/dashboard/recipes/$id'
import { Route as appauthedDashboardMealPlansCreateRouteImport } from './routes/(app)/(authed)/dashboard/meal-plans/create'
import { Route as appauthedDashboardMealPlansIdRouteImport } from './routes/(app)/(authed)/dashboard/meal-plans/$id'
import { Route as appauthedDashboardIngredientsAddRouteImport } from './routes/(app)/(authed)/dashboard/ingredients/add'

const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const appauthedRouteRoute = appauthedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => appRouteRoute,
} as any)
const appauthedARoute = appauthedARouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => appauthedRouteRoute,
} as any)
const appauthedDashboardRouteRoute = appauthedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appauthedRouteRoute,
} as any)
const appauthedDashboardIndexRoute = appauthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appauthedDashboardRouteRoute,
} as any)
const appauthedDashboardShoppingListIndexRoute =
  appauthedDashboardShoppingListIndexRouteImport.update({
    id: '/shopping-list/',
    path: '/shopping-list/',
    getParentRoute: () => appauthedDashboardRouteRoute,
  } as any)
const appauthedDashboardRecipesIndexRoute =
  appauthedDashboardRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => appauthedDashboardRouteRoute,
  } as any)
const appauthedDashboardMealPlansIndexRoute =
  appauthedDashboardMealPlansIndexRouteImport.update({
    id: '/meal-plans/',
    path: '/meal-plans/',
    getParentRoute: () => appauthedDashboardRouteRoute,
  } as any)
const appauthedDashboardIngredientsIndexRoute =
  appauthedDashboardIngredientsIndexRouteImport.update({
    id: '/ingredients/',
    path: '/ingredients/',
    getParentRoute: () => appauthedDashboardRouteRoute,
  } as any)
const appauthedDashboardRecipesCreateRoute =
  appauthedDashboardRecipesCreateRouteImport.update({
    id: '/recipes/create',
    path: '/recipes/create',
    getParentRoute: () => appauthedDashboardRouteRoute,
  } as any)
const appauthedDashboardRecipesIdRoute =
  appauthedDashboardRecipesIdRouteImport.update({
    id: '/recipes/$id',
    path: '/recipes/$id',
    getParentRoute: () => appauthedDashboardRouteRoute,
  } as any)
const appauthedDashboardMealPlansCreateRoute =
  appauthedDashboardMealPlansCreateRouteImport.update({
    id: '/meal-plans/create',
    path: '/meal-plans/create',
    getParentRoute: () => appauthedDashboardRouteRoute,
  } as any)
const appauthedDashboardMealPlansIdRoute =
  appauthedDashboardMealPlansIdRouteImport.update({
    id: '/meal-plans/$id',
    path: '/meal-plans/$id',
    getParentRoute: () => appauthedDashboardRouteRoute,
  } as any)
const appauthedDashboardIngredientsAddRoute =
  appauthedDashboardIngredientsAddRouteImport.update({
    id: '/ingredients/add',
    path: '/ingredients/add',
    getParentRoute: () => appauthedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof appauthedRouteRouteWithChildren
  '/dev': typeof DevRoute
  '/sign-in': typeof authSignInRoute
  '/dashboard': typeof appauthedDashboardRouteRouteWithChildren
  '/a': typeof appauthedARoute
  '/dashboard/': typeof appauthedDashboardIndexRoute
  '/dashboard/ingredients/add': typeof appauthedDashboardIngredientsAddRoute
  '/dashboard/meal-plans/$id': typeof appauthedDashboardMealPlansIdRoute
  '/dashboard/meal-plans/create': typeof appauthedDashboardMealPlansCreateRoute
  '/dashboard/recipes/$id': typeof appauthedDashboardRecipesIdRoute
  '/dashboard/recipes/create': typeof appauthedDashboardRecipesCreateRoute
  '/dashboard/ingredients': typeof appauthedDashboardIngredientsIndexRoute
  '/dashboard/meal-plans': typeof appauthedDashboardMealPlansIndexRoute
  '/dashboard/recipes': typeof appauthedDashboardRecipesIndexRoute
  '/dashboard/shopping-list': typeof appauthedDashboardShoppingListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appauthedRouteRouteWithChildren
  '/dev': typeof DevRoute
  '/sign-in': typeof authSignInRoute
  '/a': typeof appauthedARoute
  '/dashboard': typeof appauthedDashboardIndexRoute
  '/dashboard/ingredients/add': typeof appauthedDashboardIngredientsAddRoute
  '/dashboard/meal-plans/$id': typeof appauthedDashboardMealPlansIdRoute
  '/dashboard/meal-plans/create': typeof appauthedDashboardMealPlansCreateRoute
  '/dashboard/recipes/$id': typeof appauthedDashboardRecipesIdRoute
  '/dashboard/recipes/create': typeof appauthedDashboardRecipesCreateRoute
  '/dashboard/ingredients': typeof appauthedDashboardIngredientsIndexRoute
  '/dashboard/meal-plans': typeof appauthedDashboardMealPlansIndexRoute
  '/dashboard/recipes': typeof appauthedDashboardRecipesIndexRoute
  '/dashboard/shopping-list': typeof appauthedDashboardShoppingListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/dev': typeof DevRoute
  '/(app)/(authed)': typeof appauthedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(app)/(authed)/dashboard': typeof appauthedDashboardRouteRouteWithChildren
  '/(app)/(authed)/a': typeof appauthedARoute
  '/(app)/(authed)/dashboard/': typeof appauthedDashboardIndexRoute
  '/(app)/(authed)/dashboard/ingredients/add': typeof appauthedDashboardIngredientsAddRoute
  '/(app)/(authed)/dashboard/meal-plans/$id': typeof appauthedDashboardMealPlansIdRoute
  '/(app)/(authed)/dashboard/meal-plans/create': typeof appauthedDashboardMealPlansCreateRoute
  '/(app)/(authed)/dashboard/recipes/$id': typeof appauthedDashboardRecipesIdRoute
  '/(app)/(authed)/dashboard/recipes/create': typeof appauthedDashboardRecipesCreateRoute
  '/(app)/(authed)/dashboard/ingredients/': typeof appauthedDashboardIngredientsIndexRoute
  '/(app)/(authed)/dashboard/meal-plans/': typeof appauthedDashboardMealPlansIndexRoute
  '/(app)/(authed)/dashboard/recipes/': typeof appauthedDashboardRecipesIndexRoute
  '/(app)/(authed)/dashboard/shopping-list/': typeof appauthedDashboardShoppingListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/sign-in'
    | '/dashboard'
    | '/a'
    | '/dashboard/'
    | '/dashboard/ingredients/add'
    | '/dashboard/meal-plans/$id'
    | '/dashboard/meal-plans/create'
    | '/dashboard/recipes/$id'
    | '/dashboard/recipes/create'
    | '/dashboard/ingredients'
    | '/dashboard/meal-plans'
    | '/dashboard/recipes'
    | '/dashboard/shopping-list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev'
    | '/sign-in'
    | '/a'
    | '/dashboard'
    | '/dashboard/ingredients/add'
    | '/dashboard/meal-plans/$id'
    | '/dashboard/meal-plans/create'
    | '/dashboard/recipes/$id'
    | '/dashboard/recipes/create'
    | '/dashboard/ingredients'
    | '/dashboard/meal-plans'
    | '/dashboard/recipes'
    | '/dashboard/shopping-list'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/dev'
    | '/(app)/(authed)'
    | '/(auth)/sign-in'
    | '/(app)/(authed)/dashboard'
    | '/(app)/(authed)/a'
    | '/(app)/(authed)/dashboard/'
    | '/(app)/(authed)/dashboard/ingredients/add'
    | '/(app)/(authed)/dashboard/meal-plans/$id'
    | '/(app)/(authed)/dashboard/meal-plans/create'
    | '/(app)/(authed)/dashboard/recipes/$id'
    | '/(app)/(authed)/dashboard/recipes/create'
    | '/(app)/(authed)/dashboard/ingredients/'
    | '/(app)/(authed)/dashboard/meal-plans/'
    | '/(app)/(authed)/dashboard/recipes/'
    | '/(app)/(authed)/dashboard/shopping-list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  DevRoute: typeof DevRoute
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(authed)': {
      id: '/(app)/(authed)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appauthedRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(authed)/a': {
      id: '/(app)/(authed)/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof appauthedARouteImport
      parentRoute: typeof appauthedRouteRoute
    }
    '/(app)/(authed)/dashboard': {
      id: '/(app)/(authed)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appauthedDashboardRouteRouteImport
      parentRoute: typeof appauthedRouteRoute
    }
    '/(app)/(authed)/dashboard/': {
      id: '/(app)/(authed)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appauthedDashboardIndexRouteImport
      parentRoute: typeof appauthedDashboardRouteRoute
    }
    '/(app)/(authed)/dashboard/shopping-list/': {
      id: '/(app)/(authed)/dashboard/shopping-list/'
      path: '/shopping-list'
      fullPath: '/dashboard/shopping-list'
      preLoaderRoute: typeof appauthedDashboardShoppingListIndexRouteImport
      parentRoute: typeof appauthedDashboardRouteRoute
    }
    '/(app)/(authed)/dashboard/recipes/': {
      id: '/(app)/(authed)/dashboard/recipes/'
      path: '/recipes'
      fullPath: '/dashboard/recipes'
      preLoaderRoute: typeof appauthedDashboardRecipesIndexRouteImport
      parentRoute: typeof appauthedDashboardRouteRoute
    }
    '/(app)/(authed)/dashboard/meal-plans/': {
      id: '/(app)/(authed)/dashboard/meal-plans/'
      path: '/meal-plans'
      fullPath: '/dashboard/meal-plans'
      preLoaderRoute: typeof appauthedDashboardMealPlansIndexRouteImport
      parentRoute: typeof appauthedDashboardRouteRoute
    }
    '/(app)/(authed)/dashboard/ingredients/': {
      id: '/(app)/(authed)/dashboard/ingredients/'
      path: '/ingredients'
      fullPath: '/dashboard/ingredients'
      preLoaderRoute: typeof appauthedDashboardIngredientsIndexRouteImport
      parentRoute: typeof appauthedDashboardRouteRoute
    }
    '/(app)/(authed)/dashboard/recipes/create': {
      id: '/(app)/(authed)/dashboard/recipes/create'
      path: '/recipes/create'
      fullPath: '/dashboard/recipes/create'
      preLoaderRoute: typeof appauthedDashboardRecipesCreateRouteImport
      parentRoute: typeof appauthedDashboardRouteRoute
    }
    '/(app)/(authed)/dashboard/recipes/$id': {
      id: '/(app)/(authed)/dashboard/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/dashboard/recipes/$id'
      preLoaderRoute: typeof appauthedDashboardRecipesIdRouteImport
      parentRoute: typeof appauthedDashboardRouteRoute
    }
    '/(app)/(authed)/dashboard/meal-plans/create': {
      id: '/(app)/(authed)/dashboard/meal-plans/create'
      path: '/meal-plans/create'
      fullPath: '/dashboard/meal-plans/create'
      preLoaderRoute: typeof appauthedDashboardMealPlansCreateRouteImport
      parentRoute: typeof appauthedDashboardRouteRoute
    }
    '/(app)/(authed)/dashboard/meal-plans/$id': {
      id: '/(app)/(authed)/dashboard/meal-plans/$id'
      path: '/meal-plans/$id'
      fullPath: '/dashboard/meal-plans/$id'
      preLoaderRoute: typeof appauthedDashboardMealPlansIdRouteImport
      parentRoute: typeof appauthedDashboardRouteRoute
    }
    '/(app)/(authed)/dashboard/ingredients/add': {
      id: '/(app)/(authed)/dashboard/ingredients/add'
      path: '/ingredients/add'
      fullPath: '/dashboard/ingredients/add'
      preLoaderRoute: typeof appauthedDashboardIngredientsAddRouteImport
      parentRoute: typeof appauthedDashboardRouteRoute
    }
  }
}

interface appauthedDashboardRouteRouteChildren {
  appauthedDashboardIndexRoute: typeof appauthedDashboardIndexRoute
  appauthedDashboardIngredientsAddRoute: typeof appauthedDashboardIngredientsAddRoute
  appauthedDashboardMealPlansIdRoute: typeof appauthedDashboardMealPlansIdRoute
  appauthedDashboardMealPlansCreateRoute: typeof appauthedDashboardMealPlansCreateRoute
  appauthedDashboardRecipesIdRoute: typeof appauthedDashboardRecipesIdRoute
  appauthedDashboardRecipesCreateRoute: typeof appauthedDashboardRecipesCreateRoute
  appauthedDashboardIngredientsIndexRoute: typeof appauthedDashboardIngredientsIndexRoute
  appauthedDashboardMealPlansIndexRoute: typeof appauthedDashboardMealPlansIndexRoute
  appauthedDashboardRecipesIndexRoute: typeof appauthedDashboardRecipesIndexRoute
  appauthedDashboardShoppingListIndexRoute: typeof appauthedDashboardShoppingListIndexRoute
}

const appauthedDashboardRouteRouteChildren: appauthedDashboardRouteRouteChildren =
  {
    appauthedDashboardIndexRoute: appauthedDashboardIndexRoute,
    appauthedDashboardIngredientsAddRoute:
      appauthedDashboardIngredientsAddRoute,
    appauthedDashboardMealPlansIdRoute: appauthedDashboardMealPlansIdRoute,
    appauthedDashboardMealPlansCreateRoute:
      appauthedDashboardMealPlansCreateRoute,
    appauthedDashboardRecipesIdRoute: appauthedDashboardRecipesIdRoute,
    appauthedDashboardRecipesCreateRoute: appauthedDashboardRecipesCreateRoute,
    appauthedDashboardIngredientsIndexRoute:
      appauthedDashboardIngredientsIndexRoute,
    appauthedDashboardMealPlansIndexRoute:
      appauthedDashboardMealPlansIndexRoute,
    appauthedDashboardRecipesIndexRoute: appauthedDashboardRecipesIndexRoute,
    appauthedDashboardShoppingListIndexRoute:
      appauthedDashboardShoppingListIndexRoute,
  }

const appauthedDashboardRouteRouteWithChildren =
  appauthedDashboardRouteRoute._addFileChildren(
    appauthedDashboardRouteRouteChildren,
  )

interface appauthedRouteRouteChildren {
  appauthedDashboardRouteRoute: typeof appauthedDashboardRouteRouteWithChildren
  appauthedARoute: typeof appauthedARoute
}

const appauthedRouteRouteChildren: appauthedRouteRouteChildren = {
  appauthedDashboardRouteRoute: appauthedDashboardRouteRouteWithChildren,
  appauthedARoute: appauthedARoute,
}

const appauthedRouteRouteWithChildren = appauthedRouteRoute._addFileChildren(
  appauthedRouteRouteChildren,
)

interface appRouteRouteChildren {
  appauthedRouteRoute: typeof appauthedRouteRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appauthedRouteRoute: appauthedRouteRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  DevRoute: DevRoute,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
