/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as appauthedRouteRouteImport } from './routes/(app)/(authed)/route'
import { Route as appauthedARouteImport } from './routes/(app)/(authed)/a'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const appauthedRouteRoute = appauthedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => appRouteRoute,
} as any)
const appauthedARoute = appauthedARouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => appauthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appauthedRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/a': typeof appauthedARoute
}
export interface FileRoutesByTo {
  '/': typeof appauthedRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/a': typeof appauthedARoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/(authed)': typeof appauthedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(app)/(authed)/a': typeof appauthedARoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/a'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/a'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(app)/(authed)'
    | '/(auth)/sign-in'
    | '/(app)/(authed)/a'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(authed)': {
      id: '/(app)/(authed)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appauthedRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(authed)/a': {
      id: '/(app)/(authed)/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof appauthedARouteImport
      parentRoute: typeof appauthedRouteRoute
    }
  }
}

interface appauthedRouteRouteChildren {
  appauthedARoute: typeof appauthedARoute
}

const appauthedRouteRouteChildren: appauthedRouteRouteChildren = {
  appauthedARoute: appauthedARoute,
}

const appauthedRouteRouteWithChildren = appauthedRouteRoute._addFileChildren(
  appauthedRouteRouteChildren,
)

interface appRouteRouteChildren {
  appauthedRouteRoute: typeof appauthedRouteRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appauthedRouteRoute: appauthedRouteRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
