
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RawRecipe` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RawRecipe
 * 
 */
export type RawRecipeModel = runtime.Types.Result.DefaultSelection<Prisma.$RawRecipePayload>

export type AggregateRawRecipe = {
  _count: RawRecipeCountAggregateOutputType | null
  _avg: RawRecipeAvgAggregateOutputType | null
  _sum: RawRecipeSumAggregateOutputType | null
  _min: RawRecipeMinAggregateOutputType | null
  _max: RawRecipeMaxAggregateOutputType | null
}

export type RawRecipeAvgAggregateOutputType = {
  src_id: number | null
}

export type RawRecipeSumAggregateOutputType = {
  src_id: number | null
}

export type RawRecipeMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  name: string | null
  category: string | null
  cookTime: string | null
  prepTime: string | null
  description: string | null
  src_id: number | null
}

export type RawRecipeMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  name: string | null
  category: string | null
  cookTime: string | null
  prepTime: string | null
  description: string | null
  src_id: number | null
}

export type RawRecipeCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  name: number
  category: number
  recipeIngredientQuantities: number
  recipeIngredientParts: number
  cookTime: number
  prepTime: number
  description: number
  keywords: number
  images: number
  src_id: number
  _all: number
}


export type RawRecipeAvgAggregateInputType = {
  src_id?: true
}

export type RawRecipeSumAggregateInputType = {
  src_id?: true
}

export type RawRecipeMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  name?: true
  category?: true
  cookTime?: true
  prepTime?: true
  description?: true
  src_id?: true
}

export type RawRecipeMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  name?: true
  category?: true
  cookTime?: true
  prepTime?: true
  description?: true
  src_id?: true
}

export type RawRecipeCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  name?: true
  category?: true
  recipeIngredientQuantities?: true
  recipeIngredientParts?: true
  cookTime?: true
  prepTime?: true
  description?: true
  keywords?: true
  images?: true
  src_id?: true
  _all?: true
}

export type RawRecipeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RawRecipe to aggregate.
   */
  where?: Prisma.RawRecipeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RawRecipes to fetch.
   */
  orderBy?: Prisma.RawRecipeOrderByWithRelationInput | Prisma.RawRecipeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RawRecipeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RawRecipes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RawRecipes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RawRecipes
  **/
  _count?: true | RawRecipeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RawRecipeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RawRecipeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RawRecipeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RawRecipeMaxAggregateInputType
}

export type GetRawRecipeAggregateType<T extends RawRecipeAggregateArgs> = {
      [P in keyof T & keyof AggregateRawRecipe]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRawRecipe[P]>
    : Prisma.GetScalarType<T[P], AggregateRawRecipe[P]>
}




export type RawRecipeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RawRecipeWhereInput
  orderBy?: Prisma.RawRecipeOrderByWithAggregationInput | Prisma.RawRecipeOrderByWithAggregationInput[]
  by: Prisma.RawRecipeScalarFieldEnum[] | Prisma.RawRecipeScalarFieldEnum
  having?: Prisma.RawRecipeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RawRecipeCountAggregateInputType | true
  _avg?: RawRecipeAvgAggregateInputType
  _sum?: RawRecipeSumAggregateInputType
  _min?: RawRecipeMinAggregateInputType
  _max?: RawRecipeMaxAggregateInputType
}

export type RawRecipeGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  name: string
  category: string | null
  recipeIngredientQuantities: string[]
  recipeIngredientParts: string[]
  cookTime: string | null
  prepTime: string | null
  description: string | null
  keywords: string[]
  images: string[]
  src_id: number | null
  _count: RawRecipeCountAggregateOutputType | null
  _avg: RawRecipeAvgAggregateOutputType | null
  _sum: RawRecipeSumAggregateOutputType | null
  _min: RawRecipeMinAggregateOutputType | null
  _max: RawRecipeMaxAggregateOutputType | null
}

type GetRawRecipeGroupByPayload<T extends RawRecipeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RawRecipeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RawRecipeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RawRecipeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RawRecipeGroupByOutputType[P]>
      }
    >
  >



export type RawRecipeWhereInput = {
  AND?: Prisma.RawRecipeWhereInput | Prisma.RawRecipeWhereInput[]
  OR?: Prisma.RawRecipeWhereInput[]
  NOT?: Prisma.RawRecipeWhereInput | Prisma.RawRecipeWhereInput[]
  id?: Prisma.UuidFilter<"RawRecipe"> | string
  createdAt?: Prisma.DateTimeFilter<"RawRecipe"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RawRecipe"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"RawRecipe"> | Date | string | null
  name?: Prisma.StringFilter<"RawRecipe"> | string
  category?: Prisma.StringNullableFilter<"RawRecipe"> | string | null
  recipeIngredientQuantities?: Prisma.StringNullableListFilter<"RawRecipe">
  recipeIngredientParts?: Prisma.StringNullableListFilter<"RawRecipe">
  cookTime?: Prisma.StringNullableFilter<"RawRecipe"> | string | null
  prepTime?: Prisma.StringNullableFilter<"RawRecipe"> | string | null
  description?: Prisma.StringNullableFilter<"RawRecipe"> | string | null
  keywords?: Prisma.StringNullableListFilter<"RawRecipe">
  images?: Prisma.StringNullableListFilter<"RawRecipe">
  src_id?: Prisma.IntNullableFilter<"RawRecipe"> | number | null
}

export type RawRecipeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  recipeIngredientQuantities?: Prisma.SortOrder
  recipeIngredientParts?: Prisma.SortOrder
  cookTime?: Prisma.SortOrderInput | Prisma.SortOrder
  prepTime?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  keywords?: Prisma.SortOrder
  images?: Prisma.SortOrder
  src_id?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type RawRecipeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  src_id?: number
  AND?: Prisma.RawRecipeWhereInput | Prisma.RawRecipeWhereInput[]
  OR?: Prisma.RawRecipeWhereInput[]
  NOT?: Prisma.RawRecipeWhereInput | Prisma.RawRecipeWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"RawRecipe"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RawRecipe"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"RawRecipe"> | Date | string | null
  name?: Prisma.StringFilter<"RawRecipe"> | string
  category?: Prisma.StringNullableFilter<"RawRecipe"> | string | null
  recipeIngredientQuantities?: Prisma.StringNullableListFilter<"RawRecipe">
  recipeIngredientParts?: Prisma.StringNullableListFilter<"RawRecipe">
  cookTime?: Prisma.StringNullableFilter<"RawRecipe"> | string | null
  prepTime?: Prisma.StringNullableFilter<"RawRecipe"> | string | null
  description?: Prisma.StringNullableFilter<"RawRecipe"> | string | null
  keywords?: Prisma.StringNullableListFilter<"RawRecipe">
  images?: Prisma.StringNullableListFilter<"RawRecipe">
}, "id" | "src_id">

export type RawRecipeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  recipeIngredientQuantities?: Prisma.SortOrder
  recipeIngredientParts?: Prisma.SortOrder
  cookTime?: Prisma.SortOrderInput | Prisma.SortOrder
  prepTime?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  keywords?: Prisma.SortOrder
  images?: Prisma.SortOrder
  src_id?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.RawRecipeCountOrderByAggregateInput
  _avg?: Prisma.RawRecipeAvgOrderByAggregateInput
  _max?: Prisma.RawRecipeMaxOrderByAggregateInput
  _min?: Prisma.RawRecipeMinOrderByAggregateInput
  _sum?: Prisma.RawRecipeSumOrderByAggregateInput
}

export type RawRecipeScalarWhereWithAggregatesInput = {
  AND?: Prisma.RawRecipeScalarWhereWithAggregatesInput | Prisma.RawRecipeScalarWhereWithAggregatesInput[]
  OR?: Prisma.RawRecipeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RawRecipeScalarWhereWithAggregatesInput | Prisma.RawRecipeScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"RawRecipe"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RawRecipe"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"RawRecipe"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"RawRecipe"> | Date | string | null
  name?: Prisma.StringWithAggregatesFilter<"RawRecipe"> | string
  category?: Prisma.StringNullableWithAggregatesFilter<"RawRecipe"> | string | null
  recipeIngredientQuantities?: Prisma.StringNullableListFilter<"RawRecipe">
  recipeIngredientParts?: Prisma.StringNullableListFilter<"RawRecipe">
  cookTime?: Prisma.StringNullableWithAggregatesFilter<"RawRecipe"> | string | null
  prepTime?: Prisma.StringNullableWithAggregatesFilter<"RawRecipe"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"RawRecipe"> | string | null
  keywords?: Prisma.StringNullableListFilter<"RawRecipe">
  images?: Prisma.StringNullableListFilter<"RawRecipe">
  src_id?: Prisma.IntNullableWithAggregatesFilter<"RawRecipe"> | number | null
}

export type RawRecipeCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  name: string
  category?: string | null
  recipeIngredientQuantities?: Prisma.RawRecipeCreaterecipeIngredientQuantitiesInput | string[]
  recipeIngredientParts?: Prisma.RawRecipeCreaterecipeIngredientPartsInput | string[]
  cookTime?: string | null
  prepTime?: string | null
  description?: string | null
  keywords?: Prisma.RawRecipeCreatekeywordsInput | string[]
  images?: Prisma.RawRecipeCreateimagesInput | string[]
  src_id?: number | null
}

export type RawRecipeUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  name: string
  category?: string | null
  recipeIngredientQuantities?: Prisma.RawRecipeCreaterecipeIngredientQuantitiesInput | string[]
  recipeIngredientParts?: Prisma.RawRecipeCreaterecipeIngredientPartsInput | string[]
  cookTime?: string | null
  prepTime?: string | null
  description?: string | null
  keywords?: Prisma.RawRecipeCreatekeywordsInput | string[]
  images?: Prisma.RawRecipeCreateimagesInput | string[]
  src_id?: number | null
}

export type RawRecipeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipeIngredientQuantities?: Prisma.RawRecipeUpdaterecipeIngredientQuantitiesInput | string[]
  recipeIngredientParts?: Prisma.RawRecipeUpdaterecipeIngredientPartsInput | string[]
  cookTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prepTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  keywords?: Prisma.RawRecipeUpdatekeywordsInput | string[]
  images?: Prisma.RawRecipeUpdateimagesInput | string[]
  src_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RawRecipeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipeIngredientQuantities?: Prisma.RawRecipeUpdaterecipeIngredientQuantitiesInput | string[]
  recipeIngredientParts?: Prisma.RawRecipeUpdaterecipeIngredientPartsInput | string[]
  cookTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prepTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  keywords?: Prisma.RawRecipeUpdatekeywordsInput | string[]
  images?: Prisma.RawRecipeUpdateimagesInput | string[]
  src_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RawRecipeCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  name: string
  category?: string | null
  recipeIngredientQuantities?: Prisma.RawRecipeCreaterecipeIngredientQuantitiesInput | string[]
  recipeIngredientParts?: Prisma.RawRecipeCreaterecipeIngredientPartsInput | string[]
  cookTime?: string | null
  prepTime?: string | null
  description?: string | null
  keywords?: Prisma.RawRecipeCreatekeywordsInput | string[]
  images?: Prisma.RawRecipeCreateimagesInput | string[]
  src_id?: number | null
}

export type RawRecipeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipeIngredientQuantities?: Prisma.RawRecipeUpdaterecipeIngredientQuantitiesInput | string[]
  recipeIngredientParts?: Prisma.RawRecipeUpdaterecipeIngredientPartsInput | string[]
  cookTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prepTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  keywords?: Prisma.RawRecipeUpdatekeywordsInput | string[]
  images?: Prisma.RawRecipeUpdateimagesInput | string[]
  src_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RawRecipeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipeIngredientQuantities?: Prisma.RawRecipeUpdaterecipeIngredientQuantitiesInput | string[]
  recipeIngredientParts?: Prisma.RawRecipeUpdaterecipeIngredientPartsInput | string[]
  cookTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prepTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  keywords?: Prisma.RawRecipeUpdatekeywordsInput | string[]
  images?: Prisma.RawRecipeUpdateimagesInput | string[]
  src_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type RawRecipeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  recipeIngredientQuantities?: Prisma.SortOrder
  recipeIngredientParts?: Prisma.SortOrder
  cookTime?: Prisma.SortOrder
  prepTime?: Prisma.SortOrder
  description?: Prisma.SortOrder
  keywords?: Prisma.SortOrder
  images?: Prisma.SortOrder
  src_id?: Prisma.SortOrder
}

export type RawRecipeAvgOrderByAggregateInput = {
  src_id?: Prisma.SortOrder
}

export type RawRecipeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  cookTime?: Prisma.SortOrder
  prepTime?: Prisma.SortOrder
  description?: Prisma.SortOrder
  src_id?: Prisma.SortOrder
}

export type RawRecipeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  cookTime?: Prisma.SortOrder
  prepTime?: Prisma.SortOrder
  description?: Prisma.SortOrder
  src_id?: Prisma.SortOrder
}

export type RawRecipeSumOrderByAggregateInput = {
  src_id?: Prisma.SortOrder
}

export type RawRecipeCreaterecipeIngredientQuantitiesInput = {
  set: string[]
}

export type RawRecipeCreaterecipeIngredientPartsInput = {
  set: string[]
}

export type RawRecipeCreatekeywordsInput = {
  set: string[]
}

export type RawRecipeCreateimagesInput = {
  set: string[]
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type RawRecipeUpdaterecipeIngredientQuantitiesInput = {
  set?: string[]
  push?: string | string[]
}

export type RawRecipeUpdaterecipeIngredientPartsInput = {
  set?: string[]
  push?: string | string[]
}

export type RawRecipeUpdatekeywordsInput = {
  set?: string[]
  push?: string | string[]
}

export type RawRecipeUpdateimagesInput = {
  set?: string[]
  push?: string | string[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type RawRecipeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  name?: boolean
  category?: boolean
  recipeIngredientQuantities?: boolean
  recipeIngredientParts?: boolean
  cookTime?: boolean
  prepTime?: boolean
  description?: boolean
  keywords?: boolean
  images?: boolean
  src_id?: boolean
}, ExtArgs["result"]["rawRecipe"]>

export type RawRecipeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  name?: boolean
  category?: boolean
  recipeIngredientQuantities?: boolean
  recipeIngredientParts?: boolean
  cookTime?: boolean
  prepTime?: boolean
  description?: boolean
  keywords?: boolean
  images?: boolean
  src_id?: boolean
}, ExtArgs["result"]["rawRecipe"]>

export type RawRecipeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  name?: boolean
  category?: boolean
  recipeIngredientQuantities?: boolean
  recipeIngredientParts?: boolean
  cookTime?: boolean
  prepTime?: boolean
  description?: boolean
  keywords?: boolean
  images?: boolean
  src_id?: boolean
}, ExtArgs["result"]["rawRecipe"]>

export type RawRecipeSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  name?: boolean
  category?: boolean
  recipeIngredientQuantities?: boolean
  recipeIngredientParts?: boolean
  cookTime?: boolean
  prepTime?: boolean
  description?: boolean
  keywords?: boolean
  images?: boolean
  src_id?: boolean
}

export type RawRecipeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "deletedAt" | "name" | "category" | "recipeIngredientQuantities" | "recipeIngredientParts" | "cookTime" | "prepTime" | "description" | "keywords" | "images" | "src_id", ExtArgs["result"]["rawRecipe"]>

export type $RawRecipePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RawRecipe"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
    name: string
    category: string | null
    recipeIngredientQuantities: string[]
    recipeIngredientParts: string[]
    /**
     * ISO-8601 Duration format
     */
    cookTime: string | null
    /**
     * ISO-8601 Duration format
     */
    prepTime: string | null
    description: string | null
    keywords: string[]
    images: string[]
    src_id: number | null
  }, ExtArgs["result"]["rawRecipe"]>
  composites: {}
}

export type RawRecipeGetPayload<S extends boolean | null | undefined | RawRecipeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RawRecipePayload, S>

export type RawRecipeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RawRecipeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RawRecipeCountAggregateInputType | true
  }

export interface RawRecipeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RawRecipe'], meta: { name: 'RawRecipe' } }
  /**
   * Find zero or one RawRecipe that matches the filter.
   * @param {RawRecipeFindUniqueArgs} args - Arguments to find a RawRecipe
   * @example
   * // Get one RawRecipe
   * const rawRecipe = await prisma.rawRecipe.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RawRecipeFindUniqueArgs>(args: Prisma.SelectSubset<T, RawRecipeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RawRecipeClient<runtime.Types.Result.GetResult<Prisma.$RawRecipePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RawRecipe that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RawRecipeFindUniqueOrThrowArgs} args - Arguments to find a RawRecipe
   * @example
   * // Get one RawRecipe
   * const rawRecipe = await prisma.rawRecipe.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RawRecipeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RawRecipeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RawRecipeClient<runtime.Types.Result.GetResult<Prisma.$RawRecipePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RawRecipe that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RawRecipeFindFirstArgs} args - Arguments to find a RawRecipe
   * @example
   * // Get one RawRecipe
   * const rawRecipe = await prisma.rawRecipe.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RawRecipeFindFirstArgs>(args?: Prisma.SelectSubset<T, RawRecipeFindFirstArgs<ExtArgs>>): Prisma.Prisma__RawRecipeClient<runtime.Types.Result.GetResult<Prisma.$RawRecipePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RawRecipe that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RawRecipeFindFirstOrThrowArgs} args - Arguments to find a RawRecipe
   * @example
   * // Get one RawRecipe
   * const rawRecipe = await prisma.rawRecipe.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RawRecipeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RawRecipeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RawRecipeClient<runtime.Types.Result.GetResult<Prisma.$RawRecipePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RawRecipes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RawRecipeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RawRecipes
   * const rawRecipes = await prisma.rawRecipe.findMany()
   * 
   * // Get first 10 RawRecipes
   * const rawRecipes = await prisma.rawRecipe.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const rawRecipeWithIdOnly = await prisma.rawRecipe.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RawRecipeFindManyArgs>(args?: Prisma.SelectSubset<T, RawRecipeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RawRecipePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RawRecipe.
   * @param {RawRecipeCreateArgs} args - Arguments to create a RawRecipe.
   * @example
   * // Create one RawRecipe
   * const RawRecipe = await prisma.rawRecipe.create({
   *   data: {
   *     // ... data to create a RawRecipe
   *   }
   * })
   * 
   */
  create<T extends RawRecipeCreateArgs>(args: Prisma.SelectSubset<T, RawRecipeCreateArgs<ExtArgs>>): Prisma.Prisma__RawRecipeClient<runtime.Types.Result.GetResult<Prisma.$RawRecipePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RawRecipes.
   * @param {RawRecipeCreateManyArgs} args - Arguments to create many RawRecipes.
   * @example
   * // Create many RawRecipes
   * const rawRecipe = await prisma.rawRecipe.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RawRecipeCreateManyArgs>(args?: Prisma.SelectSubset<T, RawRecipeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RawRecipes and returns the data saved in the database.
   * @param {RawRecipeCreateManyAndReturnArgs} args - Arguments to create many RawRecipes.
   * @example
   * // Create many RawRecipes
   * const rawRecipe = await prisma.rawRecipe.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RawRecipes and only return the `id`
   * const rawRecipeWithIdOnly = await prisma.rawRecipe.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RawRecipeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RawRecipeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RawRecipePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RawRecipe.
   * @param {RawRecipeDeleteArgs} args - Arguments to delete one RawRecipe.
   * @example
   * // Delete one RawRecipe
   * const RawRecipe = await prisma.rawRecipe.delete({
   *   where: {
   *     // ... filter to delete one RawRecipe
   *   }
   * })
   * 
   */
  delete<T extends RawRecipeDeleteArgs>(args: Prisma.SelectSubset<T, RawRecipeDeleteArgs<ExtArgs>>): Prisma.Prisma__RawRecipeClient<runtime.Types.Result.GetResult<Prisma.$RawRecipePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RawRecipe.
   * @param {RawRecipeUpdateArgs} args - Arguments to update one RawRecipe.
   * @example
   * // Update one RawRecipe
   * const rawRecipe = await prisma.rawRecipe.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RawRecipeUpdateArgs>(args: Prisma.SelectSubset<T, RawRecipeUpdateArgs<ExtArgs>>): Prisma.Prisma__RawRecipeClient<runtime.Types.Result.GetResult<Prisma.$RawRecipePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RawRecipes.
   * @param {RawRecipeDeleteManyArgs} args - Arguments to filter RawRecipes to delete.
   * @example
   * // Delete a few RawRecipes
   * const { count } = await prisma.rawRecipe.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RawRecipeDeleteManyArgs>(args?: Prisma.SelectSubset<T, RawRecipeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RawRecipes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RawRecipeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RawRecipes
   * const rawRecipe = await prisma.rawRecipe.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RawRecipeUpdateManyArgs>(args: Prisma.SelectSubset<T, RawRecipeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RawRecipes and returns the data updated in the database.
   * @param {RawRecipeUpdateManyAndReturnArgs} args - Arguments to update many RawRecipes.
   * @example
   * // Update many RawRecipes
   * const rawRecipe = await prisma.rawRecipe.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RawRecipes and only return the `id`
   * const rawRecipeWithIdOnly = await prisma.rawRecipe.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RawRecipeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RawRecipeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RawRecipePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RawRecipe.
   * @param {RawRecipeUpsertArgs} args - Arguments to update or create a RawRecipe.
   * @example
   * // Update or create a RawRecipe
   * const rawRecipe = await prisma.rawRecipe.upsert({
   *   create: {
   *     // ... data to create a RawRecipe
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RawRecipe we want to update
   *   }
   * })
   */
  upsert<T extends RawRecipeUpsertArgs>(args: Prisma.SelectSubset<T, RawRecipeUpsertArgs<ExtArgs>>): Prisma.Prisma__RawRecipeClient<runtime.Types.Result.GetResult<Prisma.$RawRecipePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RawRecipes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RawRecipeCountArgs} args - Arguments to filter RawRecipes to count.
   * @example
   * // Count the number of RawRecipes
   * const count = await prisma.rawRecipe.count({
   *   where: {
   *     // ... the filter for the RawRecipes we want to count
   *   }
   * })
  **/
  count<T extends RawRecipeCountArgs>(
    args?: Prisma.Subset<T, RawRecipeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RawRecipeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RawRecipe.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RawRecipeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RawRecipeAggregateArgs>(args: Prisma.Subset<T, RawRecipeAggregateArgs>): Prisma.PrismaPromise<GetRawRecipeAggregateType<T>>

  /**
   * Group by RawRecipe.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RawRecipeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RawRecipeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RawRecipeGroupByArgs['orderBy'] }
      : { orderBy?: RawRecipeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RawRecipeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRawRecipeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RawRecipe model
 */
readonly fields: RawRecipeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RawRecipe.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RawRecipeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RawRecipe model
 */
export interface RawRecipeFieldRefs {
  readonly id: Prisma.FieldRef<"RawRecipe", 'String'>
  readonly createdAt: Prisma.FieldRef<"RawRecipe", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"RawRecipe", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"RawRecipe", 'DateTime'>
  readonly name: Prisma.FieldRef<"RawRecipe", 'String'>
  readonly category: Prisma.FieldRef<"RawRecipe", 'String'>
  readonly recipeIngredientQuantities: Prisma.FieldRef<"RawRecipe", 'String[]'>
  readonly recipeIngredientParts: Prisma.FieldRef<"RawRecipe", 'String[]'>
  readonly cookTime: Prisma.FieldRef<"RawRecipe", 'String'>
  readonly prepTime: Prisma.FieldRef<"RawRecipe", 'String'>
  readonly description: Prisma.FieldRef<"RawRecipe", 'String'>
  readonly keywords: Prisma.FieldRef<"RawRecipe", 'String[]'>
  readonly images: Prisma.FieldRef<"RawRecipe", 'String[]'>
  readonly src_id: Prisma.FieldRef<"RawRecipe", 'Int'>
}
    

// Custom InputTypes
/**
 * RawRecipe findUnique
 */
export type RawRecipeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RawRecipe
   */
  select?: Prisma.RawRecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RawRecipe
   */
  omit?: Prisma.RawRecipeOmit<ExtArgs> | null
  /**
   * Filter, which RawRecipe to fetch.
   */
  where: Prisma.RawRecipeWhereUniqueInput
}

/**
 * RawRecipe findUniqueOrThrow
 */
export type RawRecipeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RawRecipe
   */
  select?: Prisma.RawRecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RawRecipe
   */
  omit?: Prisma.RawRecipeOmit<ExtArgs> | null
  /**
   * Filter, which RawRecipe to fetch.
   */
  where: Prisma.RawRecipeWhereUniqueInput
}

/**
 * RawRecipe findFirst
 */
export type RawRecipeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RawRecipe
   */
  select?: Prisma.RawRecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RawRecipe
   */
  omit?: Prisma.RawRecipeOmit<ExtArgs> | null
  /**
   * Filter, which RawRecipe to fetch.
   */
  where?: Prisma.RawRecipeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RawRecipes to fetch.
   */
  orderBy?: Prisma.RawRecipeOrderByWithRelationInput | Prisma.RawRecipeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RawRecipes.
   */
  cursor?: Prisma.RawRecipeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RawRecipes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RawRecipes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RawRecipes.
   */
  distinct?: Prisma.RawRecipeScalarFieldEnum | Prisma.RawRecipeScalarFieldEnum[]
}

/**
 * RawRecipe findFirstOrThrow
 */
export type RawRecipeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RawRecipe
   */
  select?: Prisma.RawRecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RawRecipe
   */
  omit?: Prisma.RawRecipeOmit<ExtArgs> | null
  /**
   * Filter, which RawRecipe to fetch.
   */
  where?: Prisma.RawRecipeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RawRecipes to fetch.
   */
  orderBy?: Prisma.RawRecipeOrderByWithRelationInput | Prisma.RawRecipeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RawRecipes.
   */
  cursor?: Prisma.RawRecipeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RawRecipes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RawRecipes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RawRecipes.
   */
  distinct?: Prisma.RawRecipeScalarFieldEnum | Prisma.RawRecipeScalarFieldEnum[]
}

/**
 * RawRecipe findMany
 */
export type RawRecipeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RawRecipe
   */
  select?: Prisma.RawRecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RawRecipe
   */
  omit?: Prisma.RawRecipeOmit<ExtArgs> | null
  /**
   * Filter, which RawRecipes to fetch.
   */
  where?: Prisma.RawRecipeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RawRecipes to fetch.
   */
  orderBy?: Prisma.RawRecipeOrderByWithRelationInput | Prisma.RawRecipeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RawRecipes.
   */
  cursor?: Prisma.RawRecipeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RawRecipes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RawRecipes.
   */
  skip?: number
  distinct?: Prisma.RawRecipeScalarFieldEnum | Prisma.RawRecipeScalarFieldEnum[]
}

/**
 * RawRecipe create
 */
export type RawRecipeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RawRecipe
   */
  select?: Prisma.RawRecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RawRecipe
   */
  omit?: Prisma.RawRecipeOmit<ExtArgs> | null
  /**
   * The data needed to create a RawRecipe.
   */
  data: Prisma.XOR<Prisma.RawRecipeCreateInput, Prisma.RawRecipeUncheckedCreateInput>
}

/**
 * RawRecipe createMany
 */
export type RawRecipeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RawRecipes.
   */
  data: Prisma.RawRecipeCreateManyInput | Prisma.RawRecipeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RawRecipe createManyAndReturn
 */
export type RawRecipeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RawRecipe
   */
  select?: Prisma.RawRecipeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RawRecipe
   */
  omit?: Prisma.RawRecipeOmit<ExtArgs> | null
  /**
   * The data used to create many RawRecipes.
   */
  data: Prisma.RawRecipeCreateManyInput | Prisma.RawRecipeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RawRecipe update
 */
export type RawRecipeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RawRecipe
   */
  select?: Prisma.RawRecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RawRecipe
   */
  omit?: Prisma.RawRecipeOmit<ExtArgs> | null
  /**
   * The data needed to update a RawRecipe.
   */
  data: Prisma.XOR<Prisma.RawRecipeUpdateInput, Prisma.RawRecipeUncheckedUpdateInput>
  /**
   * Choose, which RawRecipe to update.
   */
  where: Prisma.RawRecipeWhereUniqueInput
}

/**
 * RawRecipe updateMany
 */
export type RawRecipeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RawRecipes.
   */
  data: Prisma.XOR<Prisma.RawRecipeUpdateManyMutationInput, Prisma.RawRecipeUncheckedUpdateManyInput>
  /**
   * Filter which RawRecipes to update
   */
  where?: Prisma.RawRecipeWhereInput
  /**
   * Limit how many RawRecipes to update.
   */
  limit?: number
}

/**
 * RawRecipe updateManyAndReturn
 */
export type RawRecipeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RawRecipe
   */
  select?: Prisma.RawRecipeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RawRecipe
   */
  omit?: Prisma.RawRecipeOmit<ExtArgs> | null
  /**
   * The data used to update RawRecipes.
   */
  data: Prisma.XOR<Prisma.RawRecipeUpdateManyMutationInput, Prisma.RawRecipeUncheckedUpdateManyInput>
  /**
   * Filter which RawRecipes to update
   */
  where?: Prisma.RawRecipeWhereInput
  /**
   * Limit how many RawRecipes to update.
   */
  limit?: number
}

/**
 * RawRecipe upsert
 */
export type RawRecipeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RawRecipe
   */
  select?: Prisma.RawRecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RawRecipe
   */
  omit?: Prisma.RawRecipeOmit<ExtArgs> | null
  /**
   * The filter to search for the RawRecipe to update in case it exists.
   */
  where: Prisma.RawRecipeWhereUniqueInput
  /**
   * In case the RawRecipe found by the `where` argument doesn't exist, create a new RawRecipe with this data.
   */
  create: Prisma.XOR<Prisma.RawRecipeCreateInput, Prisma.RawRecipeUncheckedCreateInput>
  /**
   * In case the RawRecipe was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RawRecipeUpdateInput, Prisma.RawRecipeUncheckedUpdateInput>
}

/**
 * RawRecipe delete
 */
export type RawRecipeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RawRecipe
   */
  select?: Prisma.RawRecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RawRecipe
   */
  omit?: Prisma.RawRecipeOmit<ExtArgs> | null
  /**
   * Filter which RawRecipe to delete.
   */
  where: Prisma.RawRecipeWhereUniqueInput
}

/**
 * RawRecipe deleteMany
 */
export type RawRecipeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RawRecipes to delete
   */
  where?: Prisma.RawRecipeWhereInput
  /**
   * Limit how many RawRecipes to delete.
   */
  limit?: number
}

/**
 * RawRecipe without action
 */
export type RawRecipeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RawRecipe
   */
  select?: Prisma.RawRecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RawRecipe
   */
  omit?: Prisma.RawRecipeOmit<ExtArgs> | null
}
